[package]
name = "disjoint-path-routing"
version = "0.1.0"
authors = ["Bram van den Heuvel <b.vandenheuvel@student.tudelft.nl>"]

[dependencies]
rand = "0.5.3"
priority-queue = "0.5.1"
itertools = "0.7.8"
fnv = "1.0.6"
